tasks:
  - init: |
      sudo apt install python3 python3-pip python3-virtualenv -y && sudo apt update -y && sudo pip3 install jupyter pandas sympy pwnedpasswords
    command: sudo jupyter-notebook
   
    
